engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
exclude_patterns:
  - "config/"
  - "dist"
  - "**/node_modules"/
  - "__tests__/"
  - "/models/"
  - "/migrations/"
  - "/seeders/"
  - "public/"
