---

version: '0.1'
services:
  web:
    build: .
    command: make start
    ports:
      - "4000:4000"
      - "8081:8081"
    volumes:
      - .:/code
      - ./.bash_history:/root/.bash_history
      - /code/node_modules/
